apiVersion: v1
kind: Service
metadata:
  name: gcsbackend
  labels:
    app: gcsbackend
spec:
  selector:
    app: gcsbackend
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcsbackend
  labels:
    app: gcsbackend
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gcsbackend
  template:
    metadata:
      labels:
        app: gcsbackend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - gcsbackend
            topologyKey: kubernetes.io/hostname
      containers:
      - name: gcsbackend
        image: acoshift/gcsbackend:1.0
        livenessProbe:
          httpGet:
            path: /
            port: 18080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 18080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: gcsbackend
  labels:
    app: gcsbackend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gcsbackend